
default_connection_name = "yanluc" 

[connections]          
[connections.yanluc]

account = "PCNSVPZ-ASB46529"
user = "yanluc"
role = "SYSADMIN"
password = "Mypassword123"
warehouse = "COMPUTE_WH"
database = "YL_DB"
schema = "INTEGRATIONS"
