name: deploy
on: [push]
jobs:
  version:
     name: "Check Snowflake CLI version"
     runs-on: ubuntu-latest
     env:
        SNOWFLAKE_CONNECTIONS_MYCONNECTION_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNTNAME: ${{ secrets.SNOWFLAKE_ACCOUNTNAME }}
        SNOWFLAKE_CONNECTIONS_MYCONNECTION_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_CONNECTIONS_MYCONNECTION_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}


     steps:
          # Checkout step is necessary if you want to use a config file from your repo
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            persist-credentials: false

          # Snowflake CLI installation
        - uses: Snowflake-Labs/snowflake-cli-action@v1
          with:
            cli-version: "latest"
            default-config-file-path: "config.toml"

          # Use the CLI
        - name: Test version
          run: |
           snow --version
           snow connection test
